// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egkwlfmgaquwanrxywah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVna3dsZm1nYXF1d2Fucnh5d2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDUyMTMsImV4cCI6MjA3NDY4MTIxM30.VP6zeYZG8wmwPTubgExU0Y7ysfKiUwXkxL8hQVsKTJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});